# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.3.dev7+gd49c9c8.d20230611'
__version_tuple__ = version_tuple = (1, 1, 3, 'dev7', 'gd49c9c8.d20230611')
